version: '3'

services:
    texture:
        image: elifesciences/sciencebeam_texture:${IMAGE_TAG}
        command: npm run start:prod
        ports:
            - "4000:4000"
        restart: always
        depends_on:
            - sciencebeam
    sciencebeam:
        image: elifesciences/sciencebeam:${SCIENCEBEAM_TAG}
        command: ./server.sh \
            --host=0.0.0.0 --port=8075 \
            --grobid-url http://grobid:8070/api
        ports:
            - "8075:8075"
        networks:
            - default
            - grobid
        restart: always
        depends_on:
            - grobid
    grobid:
        image: lfoppiano/grobid:${GROBID_TAG}
        environment:
            - JAVA_OPTS=-Xmx1g
        ports:
            - "8070:8070"
        networks:
            - grobid
        healthcheck:
            test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/8070"]
            interval: 10s
            timeout: 10s
            retries: 5
        restart: always

networks:
    default:
        internal: false
    grobid:
        internal: true
