version: '3'

services:
    texture:
        image: elifesciences/sciencebeam_texture:${IMAGE_TAG}
        command: npm run start:prod
        ports:
            - "4000:4000"
        restart: always
        depends_on:
            - sciencebeam
    sciencebeam:
        image: elifesciences/sciencebeam:${SCIENCEBEAM_TAG}
        command: ./server.sh \
            --host=0.0.0.0 --port=8075 \
            --pipeline grobid,sciencebeam_autocut \
            --grobid-url http://grobid:8070/api \
            --sciencebeam-autocut-url http://sciencebeam-autocut:8080/api/autocut \
            --sciencebeam-autocut-xpath front/article-meta/title-group/article-title
        ports:
            - "8075:8075"
        networks:
            - default
            - grobid
        restart: always
        depends_on:
            - sciencebeam-autocut
            - grobid
    sciencebeam-autocut:
        image: ${SCIENCEBEAM_AUTOCUT_REPO}:${SCIENCEBEAM_AUTOCUT_TAG}
        ports:
            - "8079:8080"
        restart: always
    grobid:
        image: lfoppiano/grobid:${GROBID_TAG}
        environment:
            - JAVA_OPTS=-Xmx1g
        ports:
            - "8070:8070"
        networks:
            - grobid
        healthcheck:
            test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/8070"]
            interval: 10s
            timeout: 10s
            retries: 5
        restart: always
    sciencebeam_biorxiv:
        image: elifesciences/sciencebeam:${SCIENCEBEAM_TAG}
        command: ./server.sh \
            --host=0.0.0.0 --port=8076 \
            --pipeline grobid \
            --grobid-url http://grobid_biorxiv:8070/api
        ports:
            - "8076:8076"
        networks:
            - grobid
        depends_on:
            - grobid_biorxiv
        restart: always
    grobid_biorxiv:
        image: ${SCIENCEBEAM_GROBID_BIORXIV_REPO}:${SCIENCEBEAM_GROBID_BIORXIV_TAG}
        environment:
            - JAVA_OPTS=-Xmx1g
            - GROBID__HEADER__USE_LABELED_ABSTRACT=false
        ports:
            - "8072:8070"
        networks:
            - grobid
        restart: always

networks:
    default:
        internal: false
    grobid:
        internal: true
